### ISSUE TITLE
記事本文のCSSの全体的な調整

### ISSUE THREAD

**Issue by chocolamint** [Wabyon/Hinata-on-premise#14]
コードブロックが連続する場合に境目がわかりづらい

**Comment by chocolamint** [comment]
タイトルを変更しました。
見出し、行間など全体的に調整したいです（QiitaのCSSに比べてbootstrapそのままは見づらいと感じる）

**Comment by mad4-red** [comment]
bootstrapをLESSで導入してるのですが、どうカスタマイズを入れるのがベストなのか手探りという感じです。
CSSについては調整と言わず、1からやり直したいところです。

**Comment by chocolamint** [comment]
私は大枠はいいと思います。

記事本文の中の各要素のマージンや色を微調整するだけで結構変わるのでは？と思っています。
- 見出しサイズの調整（全体的にでかい？）
- 行間（`line-height`）の調整（もう少し空けたい）
- `code` 要素の色調整（ちょっと強いので）
- `pre` 要素のマージン調整（段落前後に余白を）

**Comment by chocolamint** [comment]
「全体的」って言っちゃうとキリがないので一旦記事本文に適用されるデザインに限ったissueに変えました。

**Comment by mad4-red** [comment]
:+1:

**Comment by chiguniiita** [comment]
:+1:
