### ISSUE TITLE
タグ検索で「.」を含むタグを指定すると404になる

### ISSUE THREAD

**Issue by mad4-red** [Wabyon/Hinata-on-premise#20]
「.NET」など

**Comment by pianikuro** [comment]
&とか+が入ってるものも駄目ですね(404 or ランタイムエラー)
urlに指定できない文字が入っているのが原因？

http://www.seil.jp/support/management/url-encode.html

**Comment by mad4-red** [comment]
> urlに指定できない文字が入っているのが原因？

おそらくそうですね。
対応箇所が異なってくるので #33 と分けて管理します。
