### ISSUE TITLE
記事の目次が欲しい

### ISSUE THREAD

**Issue by ksuke** [Wabyon/Hinata-on-premise#26]
Qiitaにある目次機能が欲しいです。
画像でいう赤枠の部分のことです。
![default](https://cloud.githubusercontent.com/assets/6694347/9637434/b4dba628-51db-11e5-96af-dccf8a6f97b3.png)

**Comment by mad4-red** [comment]
link #12

**Comment by mad4-red** [comment]
#12と関連するかと思いましたが、本家ではHeadingにid振って、そこにリンクする目次を生成してるわけじゃなさそうですね。
クライアントサイドで目次作ってるようです。
