### ISSUE TITLE
クリップボードから画像をアップロードしたい

### ISSUE THREAD

**Issue by ksuke** [Wabyon/Hinata-on-premise#29]
GitHubのようにクリップボードから画像をアップロードできるとうれしいです。
スクリーンショットを貼り付ける場面が多そうなので。

**Comment by mad4-red** [comment]
クリップボードから画像貼り付けられたんですね…
知りませんでした

**Comment by mad4-red** [comment]
Qiitaもクリップボードからの画像貼り付けできますね

**Comment by ksuke** [comment]
このあたりが参考になるかもと思って見てました。
http://qiita.com/volpe28v@github/items/dc100c75c2371bb82a3b

**Comment by mad4-red** [comment]
http://w3c.github.io/clipboard-apis/
http://koyamay.hatenablog.com/entry/2015/06/16/190313

クロスブラウザでどうするか。難しそうですね。

**Comment by ksuke** [comment]
ですね。
実装されているサイトでも非対応のブラウザではもちろん使えず、
メッセージの出し方で工夫しているので同様の対応でいいかと考えています。

Chrome

> ![image](https://cloud.githubusercontent.com/assets/6694347/9681174/01ed7386-5337-11e5-9c1c-94287626a78d.png)

IE(11)

> ![image](https://cloud.githubusercontent.com/assets/6694347/9681150/d9db6dd0-5336-11e5-9be9-506959b21fae.png)

**Comment by chocolamint** [comment]
@ksuke 
これって #74 でクローズですか？

**Comment by ksuke** [comment]
すみません、まだマージしてません(´・ω・｀)
あと、確認していませんがコメントでは動作しない気がしています(後で気づいた)

**Comment by chocolamint** [comment]
んじゃレビューしてマージします。
の前に、コメントで動作しない件は直してもらっておk？

**Comment by chocolamint** [comment]
ん？というかPRがCloseされてるのはなぜ？？

**Comment by ksuke** [comment]
対応はやります。

`Close`されてるのは恐らく、
1. `rebase`するときに`Open`の状態だと通知がいっぱいきそうだからとりあえず`Close`しとくか(よくわかってない)
2. `rebase`うまくいかない／(^o^)＼
3. あきらめて今度ブランチ作り直そう(←ｲﾏｺｺ)
という経緯で`Close`されてると思われます。

なので、

> まだマージしてません

とか以前の問題でしたね。。。

**Comment by chocolamint** [comment]
@ksuke PRごと作り直されるってことでおｋ？

**Comment by ksuke** [comment]
ですです

**Comment by chocolamint** [comment]
:ok_hand:
