### ISSUE TITLE
ユーザーIDをあとから変えられるようにする

### ISSUE THREAD

**Issue by mad4-red** [Wabyon/Hinata-on-premise#30]
初回登録時にミスをして、あとから変えたいってなった時のために。

影響する箇所は、よくよく考えるとユーザーページのURLだけですね。
Bloqsのコンテナ名はユーザーIDで分けてますが、BloqsのURLを直に記事に埋め込む形にしてるので、途中でユーザーID変えても問題なし。

**Comment by mad4-red** [comment]
なぜユーザーIDを変更できない設計にしたか。

本家が {userid}/items/{itemid} というルーティングで、記事URLにユーザーIDを含む
↓
同じURL設計にしたい
↓
ならユーザーIDが変更可能だと記事URLも変わることになるのでダメ
↓
結局ルーティングの定義が面倒くさくなって、記事URLにユーザーIDを含めなかった←ここで思考停止

**Comment by chocolamint** [comment]
変更可でいいと思います。

AD認証してる以上、ユーザー的には不変なIDはドメインのユーザーIDという感覚がありますね。
というか、そもそもユーザーIDを決める必要性を理解しづらかったり…（ドメインユーザー名と表示名以外に何で決める必要があるの？という感覚は持ちました）
