### ISSUE TITLE
共同編集機能が欲しい

### ISSUE THREAD

**Issue by chocolamint** [Wabyon/Hinata-on-premise#40]
#38 と併せて考えたい。

一旦は編集リクエストで運用回避できるが、ゆくゆくは共同編集が欲しいと思う。
排他制御周りをどうするかは課題。

**Comment by seimyopia** [comment]
- 共同編集機能
  記事作成者が共同編集者を指定して、共同編集者であれば記事を編集できる機能
- 誰でも編集機能
  ユーザー登録していれば、誰でも記事を編集できる機能

の2パターンを考える。

#48 の機能が実装されれば、共同編集者の指定の簡易化が図れそう。

**Comment by mad4-red** [comment]
誰でも編集機能は #49 に分離しました。

こちらでは

> 記事作成者が共同編集者を指定して、共同編集者であれば記事を編集できる機能

をやっていきます。

**Comment by mad4-red** [comment]
共同編集者には「役割」の属性も実装しようと思います。
- Owner…記事の削除や共同編集者の追加・変更・削除など、記事全般に関する権限を保有
- Member…記事の編集だけ可能
