### ISSUE TITLE
タグが必須扱いされている

### ISSUE THREAD

**Issue by chocolamint** [Wabyon/Hinata-on-premise#5]
タグは0個でも投稿できていいように思います。

**Comment by mad4-red** [comment]
Azure版の時は任意にしてましたね。
本家が必須だった気がしたので同じにしてみましたが、設計上はなくても問題ないので、任意に変えます。

**Comment by chocolamint** [comment]
本家は必須なんですね…
入れずに投稿したことがなかったので知りませんでした…
